# Generated by Django 4.2.16 on 2024-11-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_activation_date_user_code_generation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_block_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
